pakker <- c("DBI",
  "configr",
  "renv",
  "tidyverse",
  "PxWebApiData",
  "arrow",
  "klassR",
  "leaflet" ,
  "getPass",
  "sf",
  "sfarrow",
  "dbplyr",
  "googleCloudStorageR",
  "shiny",
  "DT",          
  "ROracle",
  "rstudioapi",
  "httr",
  "readr",
  "knitr",
  "rmarkdown",
  "fellesr",
  "RCurl",
  "here",
  "esquisse",
  "dcmodify",
  "simputation",
  "openxlsx",
  "survey",
  "RJDemetra",
  "eurostat",
  "dggridR",
  "SSBtools",
  "easySdcTable",
  "SmallCountRounding",
  "GaussSuppression",
  "GISSB",
  "tidyfst",
  "yaml",          
  "ReGenesees", # Github (fork)
  "struktuR", # Github
  "SSBpris", # Github
  "SdcForetakPerson", # Github
  "Kostra" # Github
)

setdiff(pakker, rownames(installed.packages()))
